### ISSUE TITLE
Need a unique_id function

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/dREL#5]
As raised in https://github.com/COMCIFS/cif_core/pull/359, there are some cases where support for legacy files requires generating arbitrary identifiers that are guaranteed to be unique for each row of a category. I propose we specify this function as follows:

1. Named "unique_id" (but other ideas welcome)
2. `i = unique_id()` when called in a dREL expression generates an identifier that is guaranteed to be distinct each time it is called when looping over a category
3. When a category is looped over more than once, the generated identifier for a particular row is not guaranteed to match the previously generated value, but it is guaranteed to be distinct from all previously-generated identifiers for any other rows.
4. There is no requirement that the generated identifier is universally unique, only that it is unique for the particular category.
5. No particular implementation is specified.

**Comment by vaitkus** [comment]
I think that the 4th property might be insufficient and suggest that the identifiers should be universally unique. Consider the following example:
```
# _publ_author.id is omitted and would thus be generated automatically
loop_
_publ_author_name
'Surname, Name'
'Lastname, Firstname'

# _publ_contact_author.id links to _publ_contact_author.id
loop_
_publ_contact_author.id
_publ_contact_author.name
1 'Lastname, Firstname'
2 'Surname, Name'
```
In the given example, the `_publ_author.id` item is omitted while the `_publ_contact_author.id` item that links to it is explicitly provided. Since `_publ_author.id` values are generated automatically based on an unspecified algorithm, there is a chance that it will be assigned one of the `_publ_contact_author.id` values, thus accidentally introducing potentially incorrect relations between the two category loops. Requiring the generated identifiers to be globally unique would ensure that such incorrect relations are not established.

**Comment by jamesrhester** [comment]
Well, given that `_publ_contact_author.id` is linked to `_publ_author.id`, it should take values provided in `_publ_author.id`. If the `_publ_author.id` values are missing but `_publ_contact_author.id` is present, the CIF is invalid, and in principle no generation strategy is going to salvage the links between the two categories.

But I take the point that at least we can try not to break the file more than it is already broken. How about:

4. There is no requirement that the generated identifier is universally unique, only that it is unique amongst values for the current data name. Where values are present for child or parent data names of the present data name, a value of `missing` must be returned, to ensure no accidentally incorrect associations are created.

**Comment by vaitkus** [comment]
The example that I provide definitely describes a broken CIF that is beyond any expectations of being fixed in an automated manner. However, the main idea was indeed to highlight that even in broken CIFs the automatically generated values should not accidentally introduce new relations.

The clarification seems good. I assume, that the `missing` value refers to a concept similar to the CIF special value (`?`) and not to a text string name "missing"? Maybe "unknown" might be a better keyword then?

**Comment by jamesrhester** [comment]
Yes, `missing` is a defined dREL value represented in CIF syntax as `?`.
